//TASK 7
// var arr =["SSC", "HSC","BCS","BS","BCOM","MS","MPhil","PhD"];
// document.write("Qualifications");
// document.write("<br>");
// document.write("<br>");
// document.write("<br>");
// document.write("1) "+arr[0]);
// document.write("<br>");
// document.write("2) "+arr[1]);
// document.write("<br>");
// document.write("3) "+arr[2]);
// document.write("<br>");
// document.write("4) "+arr[3]);
// document.write("<br>");
// document.write("5) "+arr[4]);
// document.write("<br>");
// document.write("6) "+arr[5]);
// document.write("<br>");
// document.write("7) "+arr[6]);
// document.write("<br>");
// document.write("8) "+arr[7]);
//TAsk 8
// var person1 =prompt("Enter name 1");
// var person2 =prompt("Enter name 2");
// var person3 =prompt("Enter name 3");
// var persons=[person1,person2,person3];
// var marks1=prompt("Enter marks for person 1");
// var marks2=prompt("Enter marks for person 2");
// var marks3=prompt("Enter marks for person 3");
// var marks=[marks1,marks2,marks3];
// var totalmarks=500;
// document.write("Score of "+persons[0]+"is "+marks[0]+"Percentage is "+marks[0]/500*100);
// document.write("<br>");
// document.write("Score of "+persons[1]+"is "+marks[1]+"Percentage is "+marks[1]/500*100);
// document.write("<br>");
// document.write("Score of "+persons[2]+"is "+marks[2]+"Percentage is "+marks[2]/500*100);
//TASK 9
// var colors=["red","green","yellow","blue"];
// document.write(colors);
// document.write("<br>");
// var add1=prompt("What color you want to add at the beginning");
// colors.unshift(add1);
// document.write(colors);
// document.write("<br>");
// var add2=prompt("What color you want to add at the end");
// colors.push(add2);
// document.write(colors);
// var add3=prompt("What color you want to add at the beginning");
// var add4=prompt("What color you want to add at the beginning");
// colors.unshift(add3,add4);
// document.write("<br>");
// document.write(colors);
// colors.shift();
// colors.pop();
// document.write("<br>");
// document.write(colors);
// var position=prompt("At what position you want to add the colors");
// var col=prompt("What color you want to add");
// colors.splice(position,0,col);
// document.write("<br>");
// document.write(colors);
// var posRemov=prompt("From what position to start removing");
// var numToRemov=prompt("How many to remove");
// colors.splice(posRemov,numToRemov);
// document.write("<br>");
// document.write(colors);
//TASK 11
// var cities=["Karachi","Lahore","Islamabad","Quetta","Peshawar"];
// document.write(cities);
// document.write("<br>");
// var selectedCities=cities.slice(2,4);
// document.write(selectedCities);
//TASK 12
// var arr = ["This", "is","my","cat"];
// document.write("Array is "+arr);
// var string=arr.join(" ");
// document.write("<br>");
// document.write("String is "+string);
//TASK 13
// var devices=["keyboards","mouse","printer","scanner"];
// document.write("Inputs "+ devices);
// document.write("<br>");
// document.write("Out: "+ devices.shift(0));
// document.write("<br>");
// document.write("Out: "+ devices.shift(0));
// document.write("<br>");
// document.write("Out: "+ devices.shift(0));
// document.write("<br>");
// document.write("Out: "+ devices.shift(0));
// document.write("<br>");
//TASK 14
// var devices=["keyboards","mouse","printer","scanner"];
// document.write("Inputs "+ devices);
// document.write("<br>");
// document.write("Out: "+ devices.pop(0));
// document.write("<br>");
// document.write("Out: "+ devices.pop(0));
// document.write("<br>");
// document.write("Out: "+ devices.pop(0));
// document.write("<br>");
// document.write("Out: "+ devices.pop(0));
// document.write("<br>");
var phones=["Apple","Samsung","Nokia","Motrolla","Sony","Haier"];
document.write(phones[0]);
document.write("<br>");
document.write(phones[1]);
document.write("<br>");
document.write(phones[2]);
document.write("<br>");
document.write(phones[3]);
document.write("<br>");
document.write(phones[4]);
document.write("<br>");
document.write(phones[5]);
document.write("<br>");